"""create_initial_tables

Revision ID: 0975c469e0c1
Revises: 
Create Date: 2026-06-06 17:20:41.756550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0975c469e0c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regulation_updates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=True),
    sa.Column('docs_used_this_month', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('shipments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('battery_chemistry', sa.String(length=50), nullable=False),
    sa.Column('packaging_config', sa.String(length=50), nullable=False),
    sa.Column('transport_mode', sa.String(length=20), nullable=False),
    sa.Column('product_type', sa.String(length=50), nullable=True),
    sa.Column('watt_hour_rating', sa.Float(), nullable=True),
    sa.Column('lithium_content_grams', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('un_number', sa.String(length=20), nullable=True),
    sa.Column('packing_instruction', sa.String(length=20), nullable=True),
    sa.Column('section', sa.String(length=5), nullable=True),
    sa.Column('requires_shippers_declaration', sa.Boolean(), nullable=True),
    sa.Column('requires_un38_3', sa.Boolean(), nullable=True),
    sa.Column('hazard_class', sa.String(length=20), nullable=True),
    sa.Column('proper_shipping_name', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.String(length=10), nullable=True),
    sa.Column('pdf_generated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_user_id'), 'shipments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipments_user_id'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('regulation_updates')
    # ### end Alembic commands ###
