"""add_billing_fields_to_user

Revision ID: 963bd484d815
Revises: 0975c469e0c1
Create Date: 2026-06-14 00:15:42.238418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '963bd484d815'
down_revision: Union[str, None] = '0975c469e0c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lemonsqueezy_customer_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('lemonsqueezy_subscription_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('subscription_status', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('current_period_end', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('perdoc_credits', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'perdoc_credits')
    op.drop_column('users', 'current_period_end')
    op.drop_column('users', 'subscription_status')
    op.drop_column('users', 'lemonsqueezy_subscription_id')
    op.drop_column('users', 'lemonsqueezy_customer_id')
    # ### end Alembic commands ###
